export const categories = [
  { id: "fabric", label: "Прання та догляд за тканиною", labelEn: "Laundry & fabric care", icon: "IconShirt" },
  { id: "dish", label: "Миючі засоби для посуду", labelEn: "Dishwashing", icon: "IconDroplets" },
  { id: "clean", label: "Побутова хімія для прибирання", labelEn: "Household cleaning", icon: "IconRecycle" },
  { id: "personal", label: "Особиста гігієна", labelEn: "Personal care", icon: "IconHeart" },
];

export const brands = [
  { id: "grunwald", name: "GRÜNWALD", tagline: "Німецька якість для щоденного догляду за домом", taglineEn: "German-inspired quality for everyday home care", focus: "Прання, чищення", focusEn: "Laundry, cleaning" },
  { id: "wells", name: "Wells", tagline: "Ефективні рішення для дому за розумну ціну", taglineEn: "Effective home care at a fair price", focus: "Прання, посуд", focusEn: "Laundry, dishwashing" },
  { id: "sapfir", name: "Sapfir", tagline: "Перевірені формули для чистоти на кожен день", taglineEn: "Trusted formulas for everyday cleanliness", focus: "Посуд, прибирання", focusEn: "Dishwashing, cleaning" },
  { id: "tino", name: "Tino", tagline: "Турбота про родину у кожній деталі", taglineEn: "Care for your family in every detail", focus: "Гігієна, прибирання", focusEn: "Personal care, cleaning" },
];

export const products = [
  { id: "gr-gel-alpine", brand: "grunwald", category: "fabric", name: "Гель для прання «Альпійська свіжість»", nameEn: "Laundry gel \"Alpine Freshness\"", volume: "2.4 л", volumeEn: "2.4 L", purpose: "home", price: 229, desc: "Гель для машинного та ручного прання з концентрованою формулою для білих і кольорових тканин.", descEn: "Machine and hand-wash laundry gel with a concentrated formula for white and coloured fabrics.", composition: "5-15% аніонні поверхнево-активні речовини, менше 5% неіонні ПАВ, ензими, парфумерна композиція, консерванти.", compositionEn: "5-15% anionic surfactants, less than 5% non-ionic surfactants, enzymes, fragrance, preservatives." },
  { id: "gr-softener", brand: "grunwald", category: "fabric", name: "Кондиціонер для білизни", nameEn: "Fabric softener", volume: "1 л", volumeEn: "1 L", purpose: "home", price: 149, desc: "Пом'якшує тканину, полегшує прасування та надає білизні тривалий аромат свіжості.", descEn: "Softens fabric, makes ironing easier and leaves laundry with a long-lasting fresh scent.", composition: "5-15% катіонні поверхнево-активні речовини, парфумерна композиція, барвник, консерванти.", compositionEn: "5-15% cationic surfactants, fragrance, colourant, preservatives." },
  { id: "gr-gel-pro", brand: "grunwald", category: "fabric", name: "Гель для прання Professional", nameEn: "Laundry gel Professional", volume: "5 л", volumeEn: "5 L", purpose: "business", price: 899, desc: "Концентрований гель для прання у промислових обсягах — пралень, готелів та клінінгових компаній.", descEn: "Concentrated laundry gel in bulk volumes for laundries, hotels and cleaning companies.", composition: "15-30% аніонні поверхнево-активні речовини, ензими, оптичні відбілювачі, консерванти.", compositionEn: "15-30% anionic surfactants, enzymes, optical brighteners, preservatives." },
  { id: "wl-powder-color", brand: "wells", category: "fabric", name: "Порошок для прання Color", nameEn: "Laundry powder Color", volume: "3 кг", volumeEn: "3 kg", purpose: "home", price: 269, desc: "Пральний порошок для кольорових тканин, зберігає яскравість кольору при регулярному пранні.", descEn: "Laundry powder for coloured fabrics, keeps colours bright through regular washing.", composition: "15-30% аніонні ПАВ, менше 5% неіонні ПАВ, поліфосфонати, ензими, парфумерна композиція.", compositionEn: "15-30% anionic surfactants, less than 5% non-ionic surfactants, polyphosphonates, enzymes, fragrance." },
  { id: "wl-dish-lemon", brand: "wells", category: "dish", name: "Засіб для миття посуду «Лимон»", nameEn: "Dishwashing liquid \"Lemon\"", volume: "500 мл", volumeEn: "500 ml", purpose: "home", price: 79, desc: "Густий концентрат для ручного миття посуду, ефективно розчиняє жир навіть у холодній воді.", descEn: "Thick concentrate for hand dishwashing, cuts through grease even in cold water.", composition: "5-15% аніонні ПАВ, менше 5% неіонні ПАВ, глюконат натрію, ароматизатор, консерванти.", compositionEn: "5-15% anionic surfactants, less than 5% non-ionic surfactants, sodium gluconate, fragrance, preservatives." },
  { id: "wl-dish-concentrate", brand: "wells", category: "dish", name: "Засіб для миття посуду, концентрат", nameEn: "Dishwashing liquid, concentrate", volume: "5 л", volumeEn: "5 L", purpose: "business", price: 649, desc: "Концентрований засіб для миття посуду у закладах громадського харчування та на виробництві.", descEn: "Concentrated dishwashing liquid for catering businesses and production facilities.", composition: "15-30% аніонні ПАВ, глюконат натрію, консерванти, ароматизатор.", compositionEn: "15-30% anionic surfactants, sodium gluconate, preservatives, fragrance." },
  { id: "sp-tabs", brand: "sapfir", category: "dish", name: "Таблетки для посудомийних машин", nameEn: "Dishwasher tablets", volume: "40 шт", volumeEn: "40 pcs", purpose: "home", price: 319, desc: "Таблетки «все в одному» для посудомийних машин — миють, полірують та захищають від накипу.", descEn: "All-in-one dishwasher tablets — clean, shine and protect against limescale.", composition: "Карбонат натрію, полікарбоксилати, ензими, відбілювач на основі кисню, сіль.", compositionEn: "Sodium carbonate, polycarboxylates, enzymes, oxygen-based bleach, salt." },
  { id: "sp-surface", brand: "sapfir", category: "clean", name: "Універсальний засіб для чищення поверхонь", nameEn: "Universal surface cleaner", volume: "750 мл", volumeEn: "750 ml", purpose: "home", price: 99, desc: "Видаляє бруд і жирові забруднення з кухонних поверхонь, плитки та побутової техніки.", descEn: "Removes dirt and grease from kitchen surfaces, tiles and appliances.", composition: "5-15% неіонні ПАВ, менше 5% аніонні ПАВ, спирт, ароматизатор, консерванти.", compositionEn: "5-15% non-ionic surfactants, less than 5% anionic surfactants, alcohol, fragrance, preservatives." },
  { id: "tn-glass", brand: "tino", category: "clean", name: "Засіб для чищення скла та дзеркал", nameEn: "Glass & mirror cleaner", volume: "500 мл", volumeEn: "500 ml", purpose: "home", price: 89, desc: "Не залишає слідів і патьоків, підходить для скла, зеркал та глянцевих поверхонь.", descEn: "Leaves no streaks or marks, suitable for glass, mirrors and glossy surfaces.", composition: "Менше 5% неіонні ПАВ, ізопропанол, аміак, барвник, ароматизатор.", compositionEn: "Less than 5% non-ionic surfactants, isopropanol, ammonia, colourant, fragrance." },
  { id: "tn-soap-kids", brand: "tino", category: "personal", name: "Рідке мило дитяче", nameEn: "Kids' liquid soap", volume: "300 мл", volumeEn: "300 ml", purpose: "home", price: 69, desc: "Гіпоалергенне рідке мило з м'якою формулою для щоденного використання дітьми та дорослими.", descEn: "Hypoallergenic liquid soap with a gentle formula for everyday use by children and adults.", composition: "5-15% амфотерні ПАВ, менше 5% неіонні ПАВ, глицерин, пантенол, консерванти.", compositionEn: "5-15% amphoteric surfactants, less than 5% non-ionic surfactants, glycerin, panthenol, preservatives." },
];

export const news = [
  { id: "eu-cert", date: "2026-06-18", title: "Виробництво Unilife підтвердило відповідність стандартам ISO 9001", titleEn: "Unilife plant reconfirms ISO 9001 compliance", excerpt: "Проведено черговий аудит систем управління якістю на виробничих потужностях компанії.", excerptEn: "A routine quality management audit was carried out at the company's production facilities.", body: "Наприкінці червня виробничі потужності Unilife Group пройшли плановий аудит на відповідність міжнародному стандарту ISO 9001. Аудит охопив процеси контролю якості сировини, виробництва та упаковки готової продукції.\n\nПідтвердження сертифікату дозволяє компанії продовжувати постачання продукції під власними торговими марками, а також виробництво під приватними марками для мереж-партнерів.\n\nКомпанія продовжує інвестувати в модернізацію обладнання та навчання персоналу, щоб відповідати вимогам як українського, так і європейського ринків.", bodyEn: "In late June, Unilife Group's production facilities underwent a scheduled audit against the international ISO 9001 standard. The audit covered quality control of raw materials, production and finished-product packaging.\n\nConfirming the certificate lets the company continue supplying products under its own brands, as well as manufacturing private-label products for retail partners.\n\nThe company continues to invest in equipment upgrades and staff training to meet the requirements of both the Ukrainian and European markets." },
  { id: "tino-launch", date: "2026-04-02", title: "Бренд Tino розширив лінійку засобів для прибирання", titleEn: "Tino expands its cleaning product line", excerpt: "У продаж надійшли нові позиції для чищення скляних та глянцевих поверхонь.", excerptEn: "New items for cleaning glass and glossy surfaces are now on sale.", body: "Бренд Tino поповнив асортимент новими засобами для догляду за домом. Лінійка орієнтована на щоденне прибирання та розроблена з урахуванням побажань покупців щодо економічної витрати засобу.\n\nНові позиції вже доступні у роздрібних мережах-партнерах компанії та в каталозі на сайті.\n\nUnilife Group регулярно оновлює продуктові лінійки брендів на основі зворотного зв'язку від покупців та партнерів з роздрібної торгівлі.", bodyEn: "The Tino brand has expanded its home care range with new products. The line is designed for everyday cleaning and built around customer feedback on economical use.\n\nThe new items are already available at the company's retail partners and in the catalogue on this website.\n\nUnilife Group regularly updates its brand product lines based on feedback from customers and retail partners." },
  { id: "export-growth", date: "2026-02-11", title: "Unilife Group збільшує обсяги постачання на експортні ринки", titleEn: "Unilife Group increases export supply volumes", excerpt: "Компанія розширює співпрацю з міжнародними роздрібними мережами.", excerptEn: "The company is expanding cooperation with international retail chains.", body: "Unilife Group повідомляє про зростання обсягів постачання продукції на експортні ринки. Продукція під власними та приватними торговими марками компанії постачається до мереж-партнерів у кількох країнах Європи.\n\nЗростання експорту супроводжується розширенням виробничих потужностей та впровадженням додаткових ліній пакування.\n\nКомпанія розглядає подальше розширення географії постачання як один з пріоритетів розвитку на найближчі роки.", bodyEn: "Unilife Group reports growth in export supply volumes. Products under the company's own and private-label brands are supplied to retail partners in several European countries.\n\nExport growth is accompanied by expanded production capacity and additional packaging lines.\n\nThe company views further geographic expansion of supply as one of its development priorities for the coming years." },
  { id: "phosphate-free", date: "2025-11-05", title: "Частина асортименту переведена на формули нового поколінн", titleEn: "Part of the range moves to next-generation formulas", excerpt: "Компанія продовжує оновлювати рецептури засобів для прання у бік менш агресивних формул.", excerptEn: "The company continues updating laundry product formulas toward gentler alternatives.", body: "Unilife Group продовжує роботу з оновлення рецептур пральних засобів. Частина асортименту брендів GRÜNWALD та Wells переведена на формули зі зниженим вмістом фосфатів.\n\nЗміна рецептур відбувається поступово, без зміни зовнішнього вигляду упаковки, аби покупці могли продовжувати користуватися звичними продуктами без додаткових ускладнень.\n\nКомпанія слідкує за змінами у регуляторних вимогах ЄС та адаптує рецептури продукції відповідно до них.", bodyEn: "Unilife Group continues updating its laundry product formulas. Part of the GRÜNWALD and Wells ranges has moved to formulas with reduced phosphate content.\n\nThe formula change is happening gradually, without changes to packaging appearance, so customers can keep using familiar products without added complications.\n\nThe company monitors changes in EU regulatory requirements and adapts product formulas accordingly." },
];

export const partners = [
  { name: "Auchan" }, { name: "Silpo" }, { name: "Metro" }, { name: "Lidl" },
];
